# Generated by Django 4.2.6 on 2023-10-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64, verbose_name="User Name")),
                ("email", models.EmailField(max_length=64, verbose_name="Email")),
                (
                    "mobile_phone",
                    models.CharField(max_length=64, verbose_name="Mobile Phone"),
                ),
                ("password", models.CharField(max_length=64, verbose_name="Password")),
            ],
        ),
    ]
